allowBuilds:
  '@google/genai': true
  esbuild: true
  msw: true
  protobufjs: true
  sharp: true
  unrs-resolver: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
packageExtensions:
  "@liff/extensions@2.28.0":
    dependencies:
      "@liff/use": 2.28.0
